# Generated by Django 5.2.17 on 2026-10-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('session_reminder', 'Session Reminder'), ('payment_success', 'Payment Success'), ('payment_due', 'Payment Due'), ('material_added', 'Material Added'), ('note_added', 'New Note'), ('enrollment', 'Enrollment Update'), ('course_expiry', 'Course Expiry'), ('announcement', 'Announcement')], default='announcement', max_length=30),
        ),
    ]
