# Generated by Django 5.2.17 on 2026-10-01 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('instructor_name', models.CharField(max_length=150)),
                ('instructor_avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=500, null=True)),
                ('price_inr', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=4.8)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_enrolled', models.PositiveIntegerField(default=0)),
                ('duration_hours', models.PositiveIntegerField(default=10)),
                ('total_sessions', models.PositiveIntegerField(default=5)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video Lecture'), ('slides', 'Presentation Slides'), ('link', 'External Resource')], default='pdf', max_length=20)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('is_protected', models.BooleanField(default=True)),
                ('allow_download', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('price_inr', models.PositiveIntegerField()),
                ('installments', models.PositiveSmallIntegerField(default=1)),
                ('installment_amount_inr', models.PositiveIntegerField()),
                ('is_popular', models.BooleanField(default=False)),
                ('features', models.JSONField(blank=True, default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructor_name', models.CharField(max_length=150)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('meet', 'Google Meet'), ('internal', 'Learnova Live Room')], default='zoom', max_length=20)),
                ('meeting_id', models.CharField(blank=True, max_length=100)),
                ('passcode', models.CharField(blank=True, max_length=100)),
                ('meeting_url', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live Now'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course')),
            ],
        ),
    ]
