# Generated by Django 5.2.17 on 2026-10-04 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, related_name='assigned_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='note',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='duration_months',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months'), (24, '24 Months')], default=3),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='plan_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('installment', 'Installment Plan'), ('emi', 'EMI Plan')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('image', 'Image'), ('video', 'Video Lecture'), ('slides', 'Presentation Slides'), ('link', 'External Resource')], default='pdf', max_length=20),
        ),
    ]
