# Generated by Django 5.2.17 on 2026-10-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_assigned_staff_material_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='installment_amount_inr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
